# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0003_auto_20160419_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='slug',
            field=models.SlugField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='bookmarks',
            field=models.ManyToManyField(related_name='tags', to='bookmarks.Bookmark'),
        ),
    ]
