# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0004_auto_20160423_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
